In [ ]:
#Transfer Learning
#Use pre-trained model and evaluate

In [ ]:
#RNN --> Used for NLP(Natural Language processing)
# Autocomplete, google translation, Named Entity Recognition, Sentiment Analysis
# One to Many --> music generation --> single seed given
# many to one --> sentiment analysis--> output will be single rating ex- 1star,2star, etc
#many to many--> language translation --> each word converted into each different word in other language


In [ ]:
# Vanishing and exploding gradients
#To solve this problem we have two concepts -> 1. GRU, 2. LSTM --> Address the problem of shorten memory



In [ ]:
# 1.LSTM (Long short term memory)
# hidden state has long memory
# memorised the previous input while predicting current input hypothesis
# long term has forget gate to remove previous things in memory and input gate to add things in memory and output gate...so totsl 3 gates.

In [ ]:
#GRU (Gated Recurrent Unit)
#2 gates:-
#1. update gate:- how much past memory to retain
#2. reset gate:- how much past memory to forget
#GRU is more light weighted compare to LSTM

In [ ]:
#Bidirection RNN

In [ ]:
#Converting words into numbers, word embeddings

In [ ]:
#word embedding techniques
# supervesied, self supervised(word to ve, glove)

In [ ]:
#WORD EMBEDDING IN SUPERVISED LEARNING

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


In [ ]:
reviews = ['nice food',
           'amazing restaurant',
           'too good',
           'just loved it!',
           'will go again',
           'horrible food',
           'never go there',
           'poor service',
           'poor quality',
           'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])


In [ ]:
one_hot('amazing restaurant', 30)

[13, 23]

In [ ]:
vocab_size = 50
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[41, 32],
 [12, 40],
 [49, 8],
 [48, 12, 41],
 [19, 3, 31],
 [10, 32],
 [37, 3, 19],
 [33, 29],
 [33, 23],
 [1, 15]]

In [ ]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[41, 32,  0],
       [12, 40,  0],
       [49,  8,  0],
       [48, 12, 41],
       [19,  3, 31],
       [10, 32,  0],
       [37,  3, 19],
       [33, 29,  0],
       [33, 23,  0],
       [ 1, 15,  0]], dtype=int32)

In [ ]:
embedded_vector_size = 4
model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [ ]:
x = padded_reviews
y = sentiment

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_4 (Flatten)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x, y, epochs=50, verbose=0)

In [ ]:
loss, accuracy = model.evaluate(x, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 554ms/step - accuracy: 0.9000 - loss: 0.6429


0.8999999761581421

In [ ]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [ ]:
weights[41]

array([-0.05458705,  0.03157029,  0.03537695, -0.04147741], dtype=float32)

In [ ]:
weights[12]

array([-0.01389584, -0.10043853,  0.03202856, -0.0080084 ], dtype=float32)

In [ ]:
#Word2Vec
# 1. CBOW: Continuous Bag of words : predict target word given context words
# 2. Skipgram: Predict context words given target word

In [ ]:
#Implement Word2Vec in gensim

In [ ]:
!pip install gensim
!pip install python-levenshtein

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.7/161.7 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 50.0 MB/s eta 0:00:00


In [ ]:
!pip uninstall -y numpy
!pip install numpy==1.23.5  # or try 1.24.x


Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 73.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pymc 5.21.1 requires numpy>=1.25.0, but you have numpy 1.23.5 which is incompatible.
scikit-image 0.25.2 requires numpy>=1.24, but you have numpy 1.23.5 which is incompatible.
bigframes 1.40.0 requires numpy>=1.24.0, but you have numpy 1.23.5 which is incompatible.
imbalanced-learn 0.13.0 requires numpy<3,>=1.24.3, but you have numpy 1.23.5 which is incompatible.
blosc2 3.2.0 requires numpy>=1.26, but you have numpy 1.23.5 which is incompatible.
albucore 0.0.23 requires numpy>=1.24.4, but you have numpy 1.23.5 which is incompatible.
treescope 0.1.9 requires numpy>=1.25.2, but you have numpy 1.23.5 which is incompatible.
jaxlib 0.

In [ ]:
import gensim
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd
import json

# Open the JSON file and read it line by line
with open('Cell_Phones_and_Accessories_5.json', 'r') as f:
    data = []
    for line in f:
        # Try to parse each line as JSON
        # If it fails, print the line and skip it
        try:
            data.append(json.loads(line))
        except json.JSONDecodeError as e:
            print(f"Skipping invalid JSON line: {line.strip()}")
            print(f"Error: {e}")

# Create a DataFrame from the successfully parsed data
df = pd.DataFrame(data)
df

Skipping invalid JSON line: {"reviewerID": "A2IMT24918V7V7", "asin": "B002LED4II", "reviewerName": "B. Kim \"Biodiesel Bob\"", "helpful": [0, 0], "reviewText": "Good little product, definitely helps manage cord issues.  I used to tie my cord onto itself. 50/50 chance that it would unravel properly.  This makes it convenient to tie the cord on and unravel it w/o kinks and knots.  I wish it was a little bigger, thus my 4 star rating.", "overall": 4.0, "summary": "From the \"Now why didn't I think of that?\" files", "unixReviewTim
Error: Unterminated string starting at: line 1 column 492 (char 491)


reviewerID        asin                 reviewerName helpful  \
0      A30TL5EWN6DFXT  120401325X                    christina  [0, 0]   
1       ASY55RVNIL0UD  120401325X                     emily l.  [0, 0]   
2      A2TMXE2AFO7ONB  120401325X                        Erica  [0, 0]   
3       AWJ0WZQYMYFQ4  120401325X                           JM  [4, 4]   
4       ATX7CZYFXI1KW  120401325X             patrice m rogoza  [2, 3]   
...               ...         ...                          ...     ...   
11419  A2UMZDRM28IAUG  B002LED4II              Amazon Customer  [0, 0]   
11420  A1P9UMP1XSE6MI  B002LED4II              Amazon Customer  [1, 2]   
11421  A160VWZVLL6O8G  B002LED4II  Amazon Customer "melodious"  [0, 1]   
11422  A1F81SAQBP04IW  B002LED4II       Amazon Customer "Mike"  [0, 1]   
11423  A1WLASR74UDAYA  B002LED4II       Ann L. Irvin "misty14"  [0, 0]   

                                              reviewText  overall  \
0      They look good and stick good! I just don't li...      4.0   
1      These stickers work like the review says they ...      5.0   
2      These are awesome and make my phone look so st...      5.0   
3      Item arrived in great time and was in perfect ...      4.0   
4      awesome! stays on, and looks great. can be use...      5.0   
...                                                  ...      ...   
11419  Nice and tidy way to keep the cord under contr...      5.0   
11420  Only quasi-negative is that the purple is not ...      5.0   
11421  I love this cord organizer. It works better th...      5.0   
11422  I also purchased that fish-looking one which w...      5.0   
11423  Gave these as stocking stuffers this year for ...      5.0   

                                           summary  unixReviewTime  \
0                                       Looks Good      1400630400   
1                            Really great product.      1389657600   
2                                   LOVE LOVE LOVE      1403740800   
3                                            Cute!      1382313600   
4        leopard home button sticker for iphone 4s      1359849600   
...                                            ...             ...   
11419                               handy and cute      1395187200   
11420         That's purple?  Otherwise very cool.      1351555200   
11421                                 Works great!      1395446400   
11422  Works great! Keeps cord snug and un-tangled      1371340800   
11423                                    Xmas gift      1391299200   

        reviewTime  
0      05 21, 2014  
1      01 14, 2014  
2      06 26, 2014  
3      10 21, 2013  
4       02 3, 2013  
...            ...  
11419  03 19, 2014  
11420  10 30, 2012  
11421  03 22, 2014  
11422  06 16, 2013  
11423   02 2, 2014  

[11424 rows x 9 columns]

In [ ]:
df.head()

reviewerID        asin      reviewerName helpful  \
0  A30TL5EWN6DFXT  120401325X         christina  [0, 0]   
1   ASY55RVNIL0UD  120401325X          emily l.  [0, 0]   
2  A2TMXE2AFO7ONB  120401325X             Erica  [0, 0]   
3   AWJ0WZQYMYFQ4  120401325X                JM  [4, 4]   
4   ATX7CZYFXI1KW  120401325X  patrice m rogoza  [2, 3]   

                                          reviewText  overall  \
0  They look good and stick good! I just don't li...      4.0   
1  These stickers work like the review says they ...      5.0   
2  These are awesome and make my phone look so st...      5.0   
3  Item arrived in great time and was in perfect ...      4.0   
4  awesome! stays on, and looks great. can be use...      5.0   

                                     summary  unixReviewTime   reviewTime  
0                                 Looks Good      1400630400  05 21, 2014  
1                      Really great product.      1389657600  01 14, 2014  
2                             LOVE LOVE LOVE      1403740800  06 26, 2014  
3                                      Cute!      1382313600  10 21, 2013  
4  leopard home button sticker for iphone 4s      1359849600   02 3, 2013

In [ ]:
df.shape

(11424, 9)

In [ ]:
df.reviewText[0]

"They look good and stick good! I just don't like the rounded shape because I was always bumping it and Siri kept popping up and it was irritating. I just won't buy a product like this again"

In [ ]:
review_text = df.reviewText.apply(gensim.utils.simple_preprocess)
review_text

0        [they, look, good, and, stick, good, just, don...
1        [these, stickers, work, like, the, review, say...
2        [these, are, awesome, and, make, my, phone, lo...
3        [item, arrived, in, great, time, and, was, in,...
4        [awesome, stays, on, and, looks, great, can, b...
                               ...                        
11419    [nice, and, tidy, way, to, keep, the, cord, un...
11420    [only, quasi, negative, is, that, the, purple,...
11421    [love, this, cord, organizer, it, works, bette...
11422    [also, purchased, that, fish, looking, one, wh...
11423    [gave, these, as, stocking, stuffers, this, ye...
Name: reviewText, Length: 11424, dtype: object

In [ ]:
model = gensim.models.Word2Vec(
   window=10,
   min_count=2,
   workers=4
)

In [ ]:
model.build_vocab(review_text, progress_per=1000)

In [ ]:
model.epochs

5

In [ ]:
model.corpus_count


11424

In [ ]:
model.train(review_text, total_examples=model.corpus_count, epochs=model.epochs)

(4295889, 5832500)

In [ ]:
model.save('/word2vec-amazon-cell-accessories-reviews-short.model')

In [ ]:
model.wv.most_similar('bad')

[('ok', 0.6270719170570374),
 ('saying', 0.5911418795585632),
 ('breaker', 0.5804578065872192),
 ('why', 0.5678637027740479),
 ('write', 0.5615706443786621),
 ('terrible', 0.5597859621047974),
 ('stars', 0.5568310022354126),
 ('true', 0.5524147152900696),
 ('complaining', 0.5501627922058105),
 ('good', 0.5418853163719177)]

In [ ]:
model.wv.similarity(w1='cheap', w2='inexpensive')

0.6326586

In [ ]:
model.wv.similarity(w1='great', w2='iphone')

0.16232285

In [1]:
#Tensorflow Input Pipeline

In [3]:
import tensorflow as tf

In [4]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]

In [7]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [8]:
for sales in tf_dataset:
  print(sales.numpy())

21
22
-108
31
-1
32
34
31


In [9]:
for sales in tf_dataset.take(3):
  print(sales.numpy())

21
22
-108


In [10]:
tf_dataset = tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset:
  print(sales.numpy())


21
22
31
32
34
31


In [12]:
tf_dataset = tf_dataset.map(lambda x: x*72)
for sales in tf_dataset.take(5):
  print(sales.numpy())


1512
1584
2232
2304
2448


In [13]:
tf_dataset = tf_dataset.shuffle(2)
for sales in tf_dataset.take(5):
  print(sales.numpy())

1584
2232
1512
2304
2448


In [15]:
for sales_batch in tf_dataset.batch(4):
  print(sales_batch.numpy())

[1512 2232 2304 1584]
[2232 2448]


In [16]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*72).shuffle(2).batch(2)

In [17]:
for sales in tf_dataset.take(5):
  print(sales.numpy())

[1512 2232]
[1584 2304]
[2232 2448]


In [18]:
#Optimize tensorflow pipeline performance: prefetch & cache

In [19]:
#What is BERT ? Full form --> Bidirectional Encoder Representations from Transformers
#Generate contexualized embeddings
#Because there can be different meaning of same word in different sentences depend upon the context
#Google uses BERT in google search

In [20]:
import tensorflow_hub as hub
import tensorflow_text as text

In [21]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [22]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [25]:
text_test = ['nice movie indeed', 'I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [27]:
text_preprocessed['input_mask']

#CLS nice movie indeed SEP ==> therefore 5 1's in input mask

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [31]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [33]:
bert_model = hub.KerasLayer(encoder_url)
bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [34]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79177403, -0.21411912,  0.49769545, ...,  0.24465235,
        -0.47334474,  0.81758696],
       [-0.91712314, -0.47935176, -0.7865697 , ..., -0.6175175 ,
        -0.71026856,  0.921843  ]], dtype=float32)>

In [35]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292047,  0.08567817,  0.14476831, ..., -0.09677088,
          0.08722127,  0.07711085],
        [ 0.1783942 , -0.19006078,  0.5034952 , ..., -0.05869824,
          0.32717073, -0.15578493],
        [ 0.18701449, -0.43388748, -0.4887515 , ..., -0.15502778,
          0.00145182, -0.24471016],
        ...,
        [ 0.12083091,  0.12884252,  0.46453542, ...,  0.0737552 ,
          0.17441946,  0.16522075],
        [ 0.07967882, -0.01190652,  0.502254  , ...,  0.13777725,
          0.21002197,  0.00624588],
        [-0.07212701, -0.28303462,  0.59033376, ...,  0.475519  ,
          0.16668482, -0.08920349]],

       [[-0.0790059 ,  0.36335096, -0.21101595, ..., -0.17183761,
          0.16299714,  0.6724268 ],
        [ 0.27883548,  0.43716297, -0.35764822, ..., -0.04463654,
          0.38315183,  0.5887981 ],
        [ 1.2037671 ,  1.0727016 ,  0.48408663, ...,  0.24921048,
          0.407309  ,  0.40481755],
        ...,

In [39]:
len(bert_results['encoder_outputs'])

12

In [41]:
bert_results['encoder_outputs'][0]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.1290144 ,  0.00644745, -0.03614967, ...,  0.04999624,
          0.06149195, -0.02657542],
        [ 1.1753386 ,  1.2140785 ,  1.1569982 , ...,  0.11634357,
         -0.3585537 , -0.40490186],
        [ 0.03859041,  0.5386997 , -0.2108978 , ...,  0.21858197,
          0.7260168 , -1.1158606 ],
        ...,
        [-0.07587015, -0.25421894,  0.7075512 , ...,  0.50541997,
         -0.1887868 ,  0.15028352],
        [-0.16066599, -0.28089687,  0.5759707 , ...,  0.5275855 ,
         -0.11141382,  0.02887543],
        [-0.04428157, -0.20279568,  0.59093547, ...,  0.8133835 ,
         -0.39075816, -0.02601742]],

       [[ 0.18903585,  0.02752551, -0.06513745, ..., -0.00620203,
          0.15053892,  0.0316545 ],
        [ 0.5916147 ,  0.7589138 , -0.07240658, ...,  0.61903954,
          0.8292891 ,  0.16161972],
        [ 1.4460826 ,  0.44602674,  0.40990272, ...,  0.48255897,
          0.6269117 ,  0.1346341 ],
        ...,